### ISSUE TITLE
remove `tf_` prefixes so client/call-site looks better

### ISSUE THREAD

**Issue by AlexanderBrevig** [entur/gha-terraform#13]
Since we're already in the context of `gha-terraform` the `tf_` prefix seems a bit redundant.

Maybe they should simply be 

```yaml
using: entur/gha-terraform/.../plan.yml
where:
  directory: ...
  workspace: ...
  version: ...
```
